<?php
/**
 ************************************************************************
 * Copyright [2018] [RakutenConnector]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */
?>

<script>
    function copyTextToClipboard(text) {
        var textArea = document.createElement("textarea");

        textArea.style.position = 'fixed';
        textArea.style.top = 0;
        textArea.style.left = 0;

        textArea.style.width = '2em';
        textArea.style.height = '2em';

        textArea.style.padding = 0;

        textArea.style.border = 'none';
        textArea.style.outline = 'none';
        textArea.style.boxShadow = 'none';

        textArea.style.background = 'transparent';

        textArea.value = text;

        document.body.appendChild(textArea);

        textArea.select();

        try {
            var successful = document.execCommand('copy');
            var msg = successful ? '*Link copiado com sucesso.' : '*Erro ao copiar link.';
            var link = document.getElementById('link-message');

            link.innerText = msg;
        } catch (err) {
            link.innerText = msg;
            console.log(msg);
        }

        document.body.removeChild(textArea);
    }
</script>

<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
<?php if(!empty($this->getBilletUrl())): ?>
    <p>
        <button class="button" onclick="window.location.href='<?php echo $this->getBilletUrl(); ?>'">Visualizar Boleto</button>
        <button class="button" onclick="copyTextToClipboard('<?php echo $this->getBilletUrl(); ?>')">Copiar Link do Boleto</button>
    </p>
    <p><span id="link-message"></span></p>
<?php endif;?>