<?php
/**
 ************************************************************************
 * Copyright [2018] [RakutenConnector]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */
?>

<p>
    <b>Alterações de status feitas nesta tela podem não ser refletidas para o sistema GenPay.</b>
</p>
<p><b><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></b></p>

<?php if(!empty($this->getCreditCardNum())): ?>
    <span><strong>Número: </strong><?php echo $this->getCreditCardNum(); ?></span><br>
<?php endif;?>
<?php if(!empty($this->getBrand())): ?>
    <span><strong>Bandeira: </strong><?php echo $this->getBrand(); ?></span><br>
<?php endif;?>
<?php if(!empty($this->getInstallments())): ?>
        <span><strong>Parcelas: </strong><?php echo $this->getInstallments(); ?>x</span><br>
<?php endif;?>
<?php if(!empty($this->getApprovedDate())): ?>
    <span><strong>Data da Aprovação: </strong><?php echo $this->getApprovedDate(); ?></span><br>
<?php endif;?>
<?php if(!empty($this->getDashboardLink())): ?>
    <p><button class="button" onclick="window.location.href='<?php echo $this->getDashboardLink(); ?>'">Dashboard RakutenPay</button><br></p>
<?php endif;?>
<?php if(!empty($this->getLabelUrl()) && !empty($this->getTrackingUrl())): ?>
    <br><p><b>GenLog</b></p>
    <p>
        <button class="button" onclick="window.location.href='<?php echo $this->getLabelUrl(); ?>'">Gerar Etiqueta</button>
        <button class="button" onclick="window.location.href='<?php echo $this->getTrackingUrl(); ?>'">Rastreamento</button>
    </p>
<?php endif;?>
