<?php
/**
 ************************************************************************
 * Copyright [2018] [RakutenConnector]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */
?>
<?php $billetUrl = (array_key_exists('billet_url', $_GET)) ? $_GET['billet_url'] : false; ?>
    <script>
    function copyTextToClipboard(text) {
        var textArea = document.createElement("textarea");

        textArea.style.position = 'fixed';
        textArea.style.top = 0;
        textArea.style.left = 0;

        // Ensure it has a small width and height. Setting to 1px / 1em
        // doesn't work as this gives a negative w/h on some browsers.
        textArea.style.width = '2em';
        textArea.style.height = '2em';

        // We don't need padding, reducing the size if it does flash render.
        textArea.style.padding = 0;

        // Clean up any borders.
        textArea.style.border = 'none';
        textArea.style.outline = 'none';
        textArea.style.boxShadow = 'none';

        // Avoid flash of white box if rendered for any reason.
        textArea.style.background = 'transparent';


        textArea.value = text;

        document.body.appendChild(textArea);

        textArea.select();

        try {
            var successful = document.execCommand('copy');
            var msg = successful ? '*Link copiado com sucesso.' : '*Erro ao copiar link.';

        } catch (err) {
            console.log(msg);
        }

        document.body.removeChild(textArea);
    }
    window.addEventListener('load', function() {

        function modal() {
            show();
        }

        function show() {
            var modal = document.querySelector('.modal');

            modal.classList.remove('hide');
            modal.classList.add('show-modal');

        }

        function hide() {
            var modal = document.querySelector('.modal');

            modal.classList.remove('show-modal');
            modal.classList.add('hide');

        }

        var content = document.querySelector('.modal');
        var button = document.getElementById('botao');
        var close = document.getElementById('close');

        content.onclick = function() {
            hide();
        };

        button.onclick = function() {
            modal();
        };

        close.onclick = function() {
            hide();
        }

    });
    </script>

<?php if ($billetUrl != false) { ?>

    <style>

        .modal {
            visibility: hidden;
            position: fixed;
            z-index: 99;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0,0,0,0.5);
        }
        .modal-content {
            position: absolute;
            display: flex;
            justify-content: center;
            width: 50rem;
            height: 100%;
            -webkit-border-radius: 10px;
            -moz-border-radius: 10px;
            border-radius: 10px;
            left: 0;
            right: 0;
            margin: 0 auto;
            background: #fff;
            box-shadow: 2px 2px 20px #333;
        }
        .show-modal {
            visibility: visible;
            opacity: 1;
            -webkit-transition: visibility 0s, opacity 0.1s linear;
            -moz-transition: visibility 0s, opacity 0.1s linear;
            -ms-transition: visibility 0s, opacity 0.1s linear;
            -o-transition: visibility 0s, opacity 0.1s linear;
            transition: visibility 0s, opacity 0.1s linear;
        }
        iframe {
            border: none;
            margin-left: 30px;
        }
        .close {
            position: relative;
            float: right;
            width: 3.5rem;
            line-height: 3.5rem;
            text-align: center;
            cursor: pointer;
            font-size: 40px;
            font-weight: bolder;
            color: #fff;
            z-index: 100;
        }
        .hide {
            visibility: hidden;
            opacity: 0;
            -webkit-transition: visibility 0s, opacity 0.1s linear;
            -moz-transition: visibility 0s, opacity 0.1s linear;
            -ms-transition: visibility 0s, opacity 0.1s linear;
            -o-transition: visibility 0s, opacity 0.1s linear;
            transition: visibility 0s, opacity 0.1s linear;
        }

    </style>

    <div class="buttons-set">
        <button class="button" onclick="copyTextToClipboard('<?php echo $billetUrl; ?>')">Copiar Link do Boleto</button>
        <button class="modal-btn button" id="botao" >VISUALIZAR BOLETO</button>

        <div id="myModal" class="modal hide">
            <span class="close" id="close">&times;</span>

            <div class="modal-content">
                <iframe src="<?php echo $billetUrl; ?>" width="900" height="800"></iframe>
            </div>
        </div>


    </div>

<?php } ?>