<?php
/**
************************************************************************
* Copyright [2018] [RakutenConnector]
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
************************************************************************
*/
?>

<p><b><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></b></p>

<?php if(!empty($this->getCreditCardNum())): ?>
    <b>Número: </b><?php echo $this->getCreditCardNum(); ?><br>
<?php endif;?>
<?php if(!empty($this->getBrand())): ?>
    <b>Bandeira: </b><?php echo $this->getBrand(); ?><br>
<?php endif;?>
<?php if(!empty($this->getInstallments())): ?>
    <b>Parcelas: </b><?php echo $this->getInstallments(); ?>x<br>
<?php endif;?>
<?php if(!empty($this->getApprovedDate())): ?>
    <b>Data da Aprovação: </b><?php echo $this->getApprovedDate(); ?><br>
<?php endif;?>
<?php if(!empty($this->getTrackingUrl())): ?>
    <br><p><b>Rakuten Logistics</b></p>
    <p>
        <button class="button" onclick="window.location.href='<?php echo $this->getTrackingUrl(); ?>'">Rastreamento</button>
    </p>
<?php endif;?>


