<?php
/**
 ************************************************************************
 * Copyright [2018] [RakutenConnector]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */

?>
<script>


    function validateCredential() {
        jQuery.ajax('<?php echo $this->getAjaxUrl() ?>', {
            data: {
                taxvat : function () {
                    return document.querySelector('input[id*=payment_rakutenpay_cnpj]').value;
                },
                apiKey : function () {
                    return document.querySelector('input[id*=payment_rakutenpay_api_key]').value;
                },
                signature : function () {
                    return document.querySelector('input[id*=payment_rakutenpay_signature_key]').value;
                },
                environment : function () {
                    return document.querySelector('select[id*=payment_rakutenpay_environment]').value;
                }
            },
            success: function(response) {
                if (response.success === true) {
                    Modal.message("success", response.message);
                } else {
                    Modal.message("error", response.message);
                }

            },
            error: function(error) {
                Modal.message("error", error.message);
            }
        });
    }


</script>

<?php echo $this->getButtonHtml() ?>